version: '3'
services:
  mysql:
    image: "mysql"
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  php:
    image: "bananabb/ubuntu-nginx-php"
    container_name: server
    ports:
      - '8080:80'
    volumes:
      - ./laravel:/var/www
    links:
      - mysql